name: pyrosettascripts_demo
channels:
  - conda-forge
  - http://conda.ipd.uw.edu
dependencies:
  - python=3.5
  - ipython
  - ipykernel
  - numpy
  - pandas
  - scipy
  - biopython
  - seaborn
  - python-blosc
  - pyrosetta
  - dask
  - distributed
